include:
  - ./docker-compose.db.yml

services:
  cms:
    build: ./apps/cms
    container_name: cms
    environment:
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - DATABASE_URI=postgressql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - ${CMS_PORT:-5000}:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true

  web:
    build: ./apps/web
    container_name: web
    environment:
      - NODE_ENV=production
      - ORIGIN=${ORIGIN}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - DATABASE_URI=postgressql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - ${WEB_PORT:-5001}:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
