FROM node:20-alpine3.19

WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN apk update
RUN apk add --no-cache libc6-compat

COPY . .

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --no-optional